import { addDays } from 'date-fns';
import { createDefaultInvoiceNumber } from '@/lib/factuurnummerGenerator';

const today = new Date();

export const defaultInvoice = {
  id: `INV-${Date.now().toString().slice(-6)}`,
  invoiceName: '',
  invoice_number: createDefaultInvoiceNumber(today),
  invoiceDate: today,
  dueDate: addDays(today, 14),
  paymentTermDays: '14',
  companyDetails: {
    name: '',
    street: '',
    postalCode: '',
    city: '',
    country: 'Nederland',
    email: '',
    kvk: '',
    btw: '',
    iban: '',
  },
  receiverDetails: {
    companyName: '',
    contactPerson: '',
    email: '',
    phone: '',
    street: '',
    postalCode: '',
    city: '',
    country: 'Nederland',
    kvk: '',
    btw: '',
  },
  items: [
    {
      id: Date.now(),
      itemName: '',
      itemDescription: '',
      quantity: 1,
      price: 0,
      tax: '21',
      customTaxRate: '',
    },
  ],
  hoursWorked: [],
  workType: 'fixed',
  amount: 0,
  description: '',
  currency: 'EUR',
  tax: '21',
  customTaxRate: 21,
  taxIncluded: false,
  extraCosts: {
    travel: 0,
    shipping: 0,
    material: 0,
  },
  notes: '',
  terms: 'Betaling binnen 14 dagen.',
  layout: 'plain',
  pdfLanguage: 'nl',
  showFactuurBaasBranding: true,
  logo: null,
  status: 'concept',
  rememberCompanyDetails: false,
};
