import { addDays } from 'date-fns';

export const defaultInvoice = {
  id: `INV-${Date.now().toString().slice(-6)}`,
  invoiceName: '',
  invoice_number: '',
  invoiceDate: new Date(),
  dueDate: addDays(new Date(), 14),
  paymentTermDays: '14',
  companyDetails: {
    name: 'FactuurBaas.nl',
    street: '',
    postalCode: '',
    city: '',
    country: '',
    email: '',
    kvk: '',
    btw: '',
    iban: '',
  },
  receiverDetails: {
    companyName: '',
    contactPerson: '',
    email: '',
    phone: '',
    street: '',
    postalCode: '',
    city: '',
    country: '',
    kvk: '',
    btw: '',
  },
  items: [
    { id: Date.now(), itemName: '', itemDescription: '', quantity: 1, price: 0 },
  ],
  hoursWorked: [
    { id: Date.now(), date: new Date(), taskDescription: '', hours: 0 },
  ],
  workType: 'fixed',
  amount: 0,
  description: '',
  currency: 'EUR',
  tax: '21',
  customTaxRate: 21,
  taxIncluded: false,
  extraCosts: {
    travel: 0,
    shipping: 0,
    material: 0,
  },
  notes: 'Bedankt voor uw opdracht!',
  terms: 'Betaling binnen 14 dagen.',
  layout: 'plain',
  pdfLanguage: 'nl',
  logo: null,
  status: 'concept',
  rememberCompanyDetails: false,
};
